services:
  - type: web
    name: neuro-qc-bot-webhook
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_WEBHOOK_SECRET
        sync: false
      - key: MIN_TEXT_CHARS
        value: "120"
      - key: FSM_TIMEOUT
        value: "180"
      # PUBLIC_BASE_URL опционально — Render подставит RENDER_EXTERNAL_URL

